#!/bin/bash

for f in `ls files`; do
        echo file is $f
done

# You can also use this if you don't have `` on your peripherals.

##!/bin/bash

#for f in $(ls files); do
#    echo "file is $f"
#done
